# -*- coding: utf-8 -*-
"""Fibonacci Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QAA6gtCdnivjz_fci4Ag5AbtYaxKJPnn
"""

def fiboSeries(input_num):
   if input_num <= 1:
       return input_num
   else:
       return(fiboSeries(input_num-1) + fiboSeries(input_num-2))

input_num = 10
print("Fibonacci Series")

for i in range(input_num):
  print(fiboSeries(i))